### ISSUE TITLE
Licensing: Copying the keys may be a violation of established copyrights

### ISSUE THREAD

**Issue by osanimmnt** [terjew/VSKeyExtractor#1]
I'm get this message "Licensing: Copying the keys may be a violation of established copyrights", what should i do?

**Comment by terjew** [comment]
Hmm, that is new to me. At what point are you getting that message?

**Comment by osanimmnt** [comment]
when I was runing the program, I'm using VS 2017, I changed the 'record' to get it runing... any suggestion?
![image](https://user-images.githubusercontent.com/84808315/122653494-84a1b380-d10a-11eb-8e2d-0f16781572f9.png)

**Comment by terjew** [comment]
Hmm, I think there is a default value under HKEY_CLASSES_ROOT\Licenses with that content, so I believe you might have empty values for product.GUID and product.MPC. I can rewrite to not use the record syntax and post a new version after testing it here.

**Comment by terjew** [comment]
Can you try the latest version?

**Comment by mattlaq** [comment]
Thanks a lot for this application, it helped me obtain my key so I could transfer my license to a different computer.  2019 Professional.

To note though, none of my unencrypted string matched the 5x5 character pattern, so the application didn't find the key out of the box.  One of the splits included the 4x5 character ProductID I had previously found in the registry, and another contained a string formatted 8character-5character-5character-5character-5character.  I tried ignoring the first three characters of that, and it worked perfectly.

**Comment by terjew** [comment]
@mattlaq glad to hear you got it working. I am cheating a bit, as the record is really some binary serialization of a struct that I don't know the layout of, and I am parsing it as plain text with a regular expression. Did the key show up at all when you ran it unmodified, or did you need to change the code?

**Comment by terjew** [comment]
@mattlaq Could you clarify if you needed any code changes to see the 8x5x5x5x5 key?
