### ISSUE TITLE
Cannot open project in VS 2015

### ISSUE THREAD

**Issue by PyroGenesis** [terjew/VSKeyExtractor#2]
Hi,

When I open the project in VS 2015 Enterprise, I get the following message:
![image](https://user-images.githubusercontent.com/17806916/125980160-cf0bb1b5-8457-4d61-833b-4793e7526d52.png)

Looking into the output window, I found:
`C:\Users\%username%\Downloads\VSKeyExtractor-main\VSKeyExtractor.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\%username%\Downloads\VSKeyExtractor-main\VSKeyExtractor.csproj`

However, when I create a fresh C# console application and just copy `Program.cs` to it, everything works perfectly.

**Comment by terjew** [comment]
Hmm, I don't know what is the issue here. I don't have VS2015 on my machine either, so I can't easily test it. If you want, you can create pull request with the new project format and I can test it on 2019 and merge it if it works here also.

**Comment by PyroGenesis** [comment]
Done. Let me know if that works for you.

**Comment by terjew** [comment]
@PyroGenesis sorry for the delay, I completely forgot about your PR. Looks good, I merged it now. Thanks!
