### ISSUE TITLE
Detection of VS2013 Ultimate

### ISSUE THREAD

**Issue by AussieMakerGeek** [terjew/VSKeyExtractor#8]
Hi,
Thanks for your work. I recently tried to use your script to recover the key for VS2013 Ultimate but it does not detect it.
I discovered the reg key where it is stored is 06181

Adding the line:
`new Product("Visual Studio 2013 Ultimate"		  , "E79B3F9C-6543-4897-BBA5-5BFB0A02BB5C", "06181"),`

To the  program.cs enabled me to extract the key successfully.

**Comment by terjew** [comment]
Hi Drew,

Glad you find the tool useful.

Thanks for the info. If you submit a pull request with the change, I will
merge it quickly.

Thanks,
Terje

**Comment by joecare99** [comment]
I just wanted to say:
Thank you !
